Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2019-02, with the labels that each got.

#173 Expelled search and degree history
  src/app/components/group/add-group/add-group.component.html
  src/app/components/group/add-group/add-group.component.ts
  src/app/components/group/delete-group/delete-group.component.html
  src/app/components/group/delete-group/delete-group.component.ts
  src/app/components/group/group-modal/models/modal-margin.ts
  src/app/components/group/group.module.ts
  src/app/components/group/update-group/update-group.component.html
  src/app/components/group/update-group/update-group.component.ts
  src/app/components/shared/modal-wrapper/constant.ts
  src/app/components/shared/modal-wrapper/modal-wrapper.component.spec.ts
  src/app/components/shared/modal-wrapper/modal-wrapper.component.ts
  src/app/components/shared/modal-wrapper/modal-wrapper.html
  src/app/components/shared/modal-wrapper/modal-wrapper.scss
  src/app/components/shared/shared.module.ts
  src/app/components/specialization/add-specialization/add-specialization.component.html
  src/app/components/specialization/add-specialization/add-specialization.component.ts
  src/app/components/specialization/delete-specialization/delete-specialization.component.html
  src/app/components/specialization/delete-specialization/delete-specialization.component.ts
  src/app/components/specialization/specialization-form/specialization-qualification/change-qualification/change-qualification.component.html
  src/app/components/specialization/specialization-form/specialization-qualification/change-qualification/change-qualification.component.ts
  src/app/components/specialization/specialization-modal/models/modal-margin.ts
  src/app/components/specialization/specialization-modal/specialization-modal.component.html
  src/app/components/specialization/specialization-modal/specialization-modal.component.spec.ts
  src/app/components/specialization/specialization-modal/specialization-modal.component.ts
  src/app/components/specialization/specialization.module.ts
  src/app/components/specialization/update-specialization/update-specialization.component.html
  src/app/components/specialization/update-specialization/update-specialization.component.ts
  src/app/components/students/expelled-students/expelled-students.component.html
  src/app/components/students/expelled-students/expelled-students.component.scss
  src/app/components/students/expelled-students/expelled-students.component.ts
  src/app/components/students/student-all-info/student-all-info.component.html
  src/app/components/students/student-all-info/student-all-info.component.scss
  src/app/components/students/student-all-info/student-all-info.component.spec.ts
  src/app/components/students/student-all-info/student-all-info.component.ts
  src/app/components/students/student-degree-history/ExpelsAndRenews.ts
  src/app/components/students/student-degree-history/student-degree-history.component.html
  src/app/components/students/student-degree-history/student-degree-history.component.scss
  src/app/components/students/student-degree-history/student-degree-history.component.spec.ts
  src/app/components/students/student-degree-history/student-degree-history.component.ts
  src/app/components/students/student-degree-info-modal/student-degree-info-modal.component.html
  src/app/components/students/student-degree-info-modal/student-degree-info-modal.component.scss
  src/app/components/students/student-degree-info-modal/student-degree-info-modal.component.spec.ts
  src/app/components/students/student-degree-info-modal/student-degree-info-modal.component.ts
  src/app/components/students/student-degree-info/student-degree-info.component.html
  src/app/components/students/student-degree-info/student-degree-info.component.ts
  src/app/components/students/student-personal-info-modal/student-personal-info-modal.component.html
  src/app/components/students/student-personal-info-modal/student-personal-info-modal.component.scss
  src/app/components/students/student-personal-info-modal/student-personal-info-modal.component.spec.ts
  src/app/components/students/student-personal-info-modal/student-personal-info-modal.component.ts
  src/app/components/students/student-personal-info/student-personal-info.component.html
  src/app/components/students/student-personal-info/student-personal-info.component.scss
  src/app/components/students/student-personal-info/student-personal-info.component.ts
  src/app/components/students/students-search/students-search.component.html
  src/app/components/students/students-search/students-search.component.ts
  src/app/components/students/students.component.html
  src/app/components/students/students.module.ts
  src/app/services/student.service.ts
Labels: new feature

#174 Add specialization code field to add/edit dialogs
  src/app/components/specialization/specialization-form/specialization-form.component.html
  src/app/components/specialization/specialization-form/specialization-form.component.ts
  src/app/models/Specialization.ts
Labels: enhancement

#177 Worker of foreign faculty can get course for group from all faculty
  src/app/components/courses-for-groups/courses-for-groups.component.ts
  src/app/services/group.service.ts
Labels: enhancement

#169 Use ag-grid on student component without reloading
  package-lock.json
  package.json
  src/app/components/shared/utils.ts
  src/app/components/students/assign-record-book-number-to-students/assign-record-book-number-to-students.component.ts
  src/app/components/students/assign-students-to-group/assign-students-to-group.component.html
  src/app/components/students/assign-students-to-group/assign-students-to-group.component.ts
  src/app/components/students/constants.js
  src/app/components/students/constants.ts
  src/app/components/students/expelled-students/expelled-students.component.html
  src/app/components/students/expelled-students/expelled-students.component.ts
  src/app/components/students/group-filter/group-filter.component.html
  src/app/components/students/group-filter/group-filter.component.scss
  src/app/components/students/group-filter/group-filter.component.spec.ts
  src/app/components/students/group-filter/group-filter.component.ts
  src/app/components/students/payment-filter/payment-filter.component.html
  src/app/components/students/payment-filter/payment-filter.component.scss
  src/app/components/students/payment-filter/payment-filter.component.spec.ts
  src/app/components/students/payment-filter/payment-filter.component.ts
  src/app/components/students/stop-academic-vacation/stop-academic-vacation.component.ts
  src/app/components/students/student-degree-info-modal/student-degree-info-modal.component.html
  src/app/components/students/student-degree-info-modal/student-degree-info-modal.component.ts
  src/app/components/students/student-degree-info/student-degree-info.component.html
  src/app/components/students/student-degree-info/student-degree-info.component.ts
  src/app/components/students/student-personal-info-modal/student-personal-info-modal.component.html
  src/app/components/students/student-personal-info-modal/student-personal-info-modal.component.ts
  src/app/components/students/student-personal-info/student-personal-info.component.ts
  src/app/components/students/students-columns/students-columns.component.ts
  src/app/components/students/students-filters/students-filters.component.html
  src/app/components/students/students-filters/students-filters.component.scss
  src/app/components/students/students-filters/students-filters.component.spec.ts
  src/app/components/students/students-filters/students-filters.component.ts
  src/app/components/students/students-in-vacation/students-in-vacation.component.html
  src/app/components/students/students-in-vacation/students-in-vacation.component.ts
  src/app/components/students/students-search/students-search.component.html
  src/app/components/students/students-search/students-search.component.ts
  src/app/components/students/students-table/students-table.component.html
  src/app/components/students/students-table/students-table.component.scss
  src/app/components/students/students-table/students-table.component.spec.ts
  src/app/components/students/students-table/students-table.component.ts
  src/app/components/students/students.component.html
  src/app/components/students/students.component.scss
  src/app/components/students/students.component.ts
  src/app/components/students/students.module.ts
  src/app/models/Student.ts
  src/styles.scss
Labels: enhancement, refactoring

#178 Worker can get speciality that not used in this faculty before
  src/app/components/specialization/specialization-form/specialization-form.component.html
  src/app/components/specialization/specialization-form/specialization-form.component.scss
  src/app/components/specialization/specialization-form/specialization-form.component.ts
  src/app/services/speciality.service.ts
Labels: enhancement

#180 getSpecialities method now return only active speciality (#179)
  src/app/services/speciality.service.ts
Labels: bug
