Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2019-06, with the labels that each got.

#287 230 feat/display exist courses for administrator
  package.json
  src/app/components/app/app-routes.ts
  src/app/components/app/header/header.component.html
  src/app/components/course/column-set.ts
  src/app/components/course/course.component.html
  src/app/components/course/course.component.scss
  src/app/components/course/course.component.spec.ts
  src/app/components/course/course.component.ts
  src/app/components/course/course.module.ts
  src/app/components/course/models/CourseFilter.ts
  src/app/components/course/models/CourseNameSearchParam.enum.ts
  src/app/components/course/models/KnowledgeControlType.enum.ts
  src/app/models/course/CoursePagination.ts
  src/app/services/course.service.ts
  src/app/services/index.ts
Labels: new feature

#289 #288 grades: enhance: change color and border size
  src/app/components/grade/grade-statement/statement.component.ts
  src/app/components/grade/grade.component.ts
  src/app/components/grade/grades-table/grades-table.component.html
  src/app/components/grade/grades-table/grades-table.component.scss
  src/app/models/Grade.ts
Labels: enhancement

#290 #248 students-tables: fix: search with filters
  src/app/components/students/expelled-students/expelled-students.component.html
  src/app/components/students/expelled-students/expelled-students.component.ts
  src/app/components/students/students-in-vacation/students-in-vacation.component.html
  src/app/components/students/students-in-vacation/students-in-vacation.component.ts
  src/app/components/students/students-search/students-search.component.ts
  src/app/components/students/students-table/students-table.component.ts
  src/app/components/students/students.component.html
  src/app/components/students/students.component.ts
Labels: bug

#294 262/show final points
  src/app/components/students/student-stipend/student-stipend.component.html
  src/app/components/students/student-stipend/student-stipend.component.scss
  src/app/components/students/student-stipend/student-stipend.component.ts
  src/app/models/basemodels/Person.ts
  src/app/models/student-stipend/StudentStipendInfo.ts
  src/app/services/student-stipend.service.ts
Labels: new feature

#291 197/198 new feature/finish study year
  src/app/components/app/app-routes.ts
  src/app/components/app/header/header.component.html
  src/app/components/finish-study-year/finish-study-year.component.html
  src/app/components/finish-study-year/finish-study-year.component.scss
  src/app/components/finish-study-year/finish-study-year.component.spec.ts
  src/app/components/finish-study-year/finish-study-year.component.ts
  src/app/components/finish-study-year/finish-study-year.module.ts
  src/app/components/finish-study-year/groups-table/groups-table.component.html
  src/app/components/finish-study-year/groups-table/groups-table.component.scss
  src/app/components/finish-study-year/groups-table/groups-table.component.spec.ts
  src/app/components/finish-study-year/groups-table/groups-table.component.ts
  src/app/components/shared/utils.ts
  src/app/models/degree.enum.ts
  src/app/services/index.ts
  src/app/services/study-year-finish.service.spec.ts
  src/app/services/study-year-finish.service.ts
Labels: new feature

#298 297 enhance/set dates diploma number synchronization
  src/app/components/reports/debtors-statistics/debtor-statistics.component.ts
  src/app/components/shared/utils.ts
  src/app/components/students/edebo-diploma-number/edebo-diploma-number.component.html
  src/app/components/students/edebo-diploma-number/edebo-diploma-number.component.scss
  src/app/components/students/edebo-diploma-number/edebo-diploma-number.component.ts
  src/app/models/basemodels/Person.ts
  src/app/models/edebo-diploma-number/DiplomaAndSynchronizedStudentDTO.ts
  src/app/models/edebo-diploma-number/DiplomaNumberForSaveDTO.ts
  src/app/services/edebo-diploma-number.service.ts
Labels: enhancement, refactoring

#299 296 enhance/sticky grade table
  src/app/components/grade/grade-statement/grade-statement-table/grade-statement-table.component.html
  src/app/components/grade/grades-table/grades-table.component.html
  src/app/components/grade/grades-table/grades-table.component.scss
Labels: enhancement
