Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2019-05, with the labels that each got.

#269 255-teachers
  src/app/components/teachers/add-teacher/add-teacher.component.html
  src/app/components/teachers/add-teacher/add-teacher.component.ts
  src/app/components/teachers/columns-def.ts
  src/app/components/teachers/delete-teacher/delete-teacher.component.html
  src/app/components/teachers/delete-teacher/delete-teacher.component.scss
  src/app/components/teachers/delete-teacher/delete-teacher.component.spec.ts
  src/app/components/teachers/delete-teacher/delete-teacher.component.ts
  src/app/components/teachers/teacher-form/teacher-form.component.html
  src/app/components/teachers/teacher-form/teacher-form.component.scss
  src/app/components/teachers/teacher-form/teacher-form.component.ts
  src/app/components/teachers/teachers.component.html
  src/app/components/teachers/teachers.component.scss
  src/app/components/teachers/teachers.component.ts
  src/app/components/teachers/teachers.module.ts
  src/app/components/teachers/update-teacher/update-teacher.component.html
  src/app/components/teachers/update-teacher/update-teacher.component.scss
  src/app/components/teachers/update-teacher/update-teacher.component.spec.ts
  src/app/components/teachers/update-teacher/update-teacher.component.ts
  src/app/models/Position.ts
  src/app/models/Teacher.ts
  src/app/services/index.ts
  src/app/services/position.service.ts
  src/app/services/teacher.service.ts
Labels: new feature

#274 257 departments
  package-lock.json
  src/app/components/app/app-routes.ts
  src/app/components/app/header/header.component.html
  src/app/components/department/add-department/add-department.component.html
  src/app/components/department/add-department/add-department.component.scss
  src/app/components/department/add-department/add-department.component.spec.ts
  src/app/components/department/add-department/add-department.component.ts
  src/app/components/department/columns-def-department.ts
  src/app/components/department/delete-department/delete-department.component.html
  src/app/components/department/delete-department/delete-department.component.scss
  src/app/components/department/delete-department/delete-department.component.spec.ts
  src/app/components/department/delete-department/delete-department.component.ts
  src/app/components/department/department-form/department-form.component.html
  src/app/components/department/department-form/department-form.component.scss
  src/app/components/department/department-form/department-form.component.spec.ts
  src/app/components/department/department-form/department-form.component.ts
  src/app/components/department/department-routing.module.ts
  src/app/components/department/department.component.html
  src/app/components/department/department.component.scss
  src/app/components/department/department.component.spec.ts
  src/app/components/department/department.component.ts
  src/app/components/department/department.module.ts
  src/app/components/department/update-department/update-department.component.html
  src/app/components/department/update-department/update-department.component.scss
  src/app/components/department/update-department/update-department.component.spec.ts
  src/app/components/department/update-department/update-department.component.ts
  src/app/services/department.service.ts
Labels: new feature

#276 254 foreign students
  src/app/components/courses-for-groups/courses-for-groups.component.html
  src/app/components/courses-for-groups/courses-for-groups.component.ts
  src/app/components/courses-for-groups/courses-for-groups.module.ts
  src/app/components/courses-for-groups/groups-different-dialog/groups-different-dialog.component.html
  src/app/components/courses-for-groups/groups-different-dialog/groups-different-dialog.component.scss
  src/app/components/courses-for-groups/groups-different-dialog/groups-different-dialog.component.spec.ts
  src/app/components/courses-for-groups/groups-different-dialog/groups-different-dialog.component.ts
  src/app/models/ForeignCourses.ts
  src/app/services/course-for-group.service.ts
Labels: new feature

#277 279 Refactor-bugfix/grades
  src/app/components/grade/EmptyGrade.ts
  src/app/components/grade/grade-statement/grade-statement-table/grade-statement-table.component.html
  src/app/components/grade/grade-statement/grade-statement-table/grade-statement-table.component.ts
  src/app/components/grade/grade-statement/statement.component.html
  src/app/components/grade/grade-statement/statement.component.ts
  src/app/components/grade/grade.component.html
  src/app/components/grade/grade.component.ts
  src/app/components/grade/grades-panel/grades-panel.component.ts
  src/app/components/grade/grades-table/grades-table.component.html
  src/app/components/grade/grades-table/grades-table.component.ts
  src/app/components/grade/models/PostGrade.ts
  src/app/models/CourseForGroup.ts
  src/app/models/Grade.ts
  src/app/models/StudentDegree.ts
Labels: bug, refactoring

#284 272 feat/academic difference for grades
  src/app/components/grade/grade.component.html
  src/app/components/grade/grade.component.ts
  src/app/components/grade/grades-table/grades-table.component.html
  src/app/components/grade/grades-table/grades-table.component.ts
  src/app/components/grade/models/GradeUpdateAcademicDifference.ts
  src/app/services/grade.service.ts
Labels: new feature

#283 #282 fix validator: change : change validator
  src/app/components/department/department-form/department-form.component.ts
Labels: bug

#285 #280: on time for grades: add: ability to change on time property
  src/app/components/grade/grade.component.html
  src/app/components/grade/grade.component.ts
  src/app/components/grade/grade.module.ts
  src/app/components/grade/grades-table/grades-table.component.html
  src/app/components/grade/grades-table/grades-table.component.scss
  src/app/components/grade/grades-table/grades-table.component.ts
  src/app/components/grade/models/PostGrade.ts
  src/app/services/grade.service.ts
Labels: new feature
