Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2019-09, with the labels that each got.

#295 Form a consolidated document
  src/app/components/app/app-routes.ts
  src/app/components/app/header/header.component.html
  src/app/components/consolidated-exam-report/consolidated-exam-report.component.html
  src/app/components/consolidated-exam-report/consolidated-exam-report.component.scss
  src/app/components/consolidated-exam-report/consolidated-exam-report.component.ts
  src/app/components/consolidated-exam-report/consolidated-exam-report.module.ts
  src/app/services/consolidated-exam-report.service.ts
  src/app/services/index.ts
Labels: new feature

#324 315 enchancement/switch groups
  src/app/components/group/group.component.html
  src/app/components/group/group.component.scss
  src/app/components/group/group.component.ts
  src/app/components/group/group.module.ts
  src/app/services/group.service.ts
Labels: enhancement

#325 323 feat/groups recovery
  src/app/components/group/group.component.html
  src/app/components/group/group.component.ts
  src/app/components/group/group.module.ts
  src/app/components/group/recovery-group/recovery-group.component.html
  src/app/components/group/recovery-group/recovery-group.component.scss
  src/app/components/group/recovery-group/recovery-group.component.spec.ts
  src/app/components/group/recovery-group/recovery-group.component.ts
  src/app/services/group.service.ts
Labels: new feature

#327 326: remove: needless block else in group component OnDeleteGroup method
  src/app/components/group/group.component.ts
Labels: UX Team, bug
