Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2019-03, with the labels that each got.

#196 Debtors statistics
  src/app/components/app/app-routes.ts
  src/app/components/app/header/header.component.html
  src/app/components/reports/debtors-statistics/debtor-statistics.component.html
  src/app/components/reports/debtors-statistics/debtor-statistics.component.scss
  src/app/components/reports/debtors-statistics/debtor-statistics.component.spec.ts
  src/app/components/reports/debtors-statistics/debtor-statistics.component.ts
  src/app/components/reports/reports.module.ts
  src/app/models/reports/debtors-statistics/SpecializationDebtorStatistics.ts
  src/app/models/reports/debtors-statistics/SpecializationDebtorsYearStatistics.ts
  src/app/models/reports/debtors-statistics/SpecializationWithDebtorsStatistics.ts
  src/app/pipes/abbreviated-name.pipe.spec.ts
  src/app/pipes/abbreviated-name.pipe.ts
  src/app/pipes/maps-keys.pipe.spec.ts
  src/app/pipes/maps-keys.pipe.ts
  src/app/pipes/pipe.module.ts
  src/app/services/debtor-statistics.service.spec.ts
  src/app/services/debtor-statistics.service.ts
Labels: new feature

#187 Ngx bootstrap only
  package-lock.json
  package.json
  src/app/components/courses-for-groups/added-courses/added-courses.component.ts
  src/app/components/courses-for-groups/copy-courses-dialog/copy-courses-dialog.component.html
  src/app/components/courses-for-groups/copy-courses-dialog/copy-courses-dialog.component.scss
  src/app/components/courses-for-groups/copy-courses-dialog/copy-courses-dialog.component.ts
  src/app/components/courses-for-groups/course-creation/course-creation.component.html
  src/app/components/courses-for-groups/course-creation/course-creation.component.ts
  src/app/components/courses-for-groups/courses-for-groups.component.html
  src/app/components/courses-for-groups/courses-for-groups.component.ts
  src/app/components/courses-for-groups/courses-for-groups.module.ts
  src/app/components/courses-for-groups/edit-dialog/edit-dialog.component.html
  src/app/components/courses-for-groups/edit-dialog/edit-dialog.component.scss
  src/app/components/courses-for-groups/edit-dialog/edit-dialog.component.ts
  src/app/components/courses-for-groups/studied-courses/studied-courses.component.ts
  src/app/components/courses-for-groups/teacher-dialog/teacher-dialog.component.html
  src/app/components/courses-for-groups/teacher-dialog/teacher-dialog.component.scss
  src/app/components/courses-for-groups/teacher-dialog/teacher-dialog.component.ts
  src/app/components/diploma-supplement/diploma-supplement.component.ts
  src/app/components/diploma-supplement/diploma-supplement.module.ts
  src/app/components/diploma-supplement/students-data-check/students-data-check.component.html
  src/app/components/diploma-supplement/students-data-check/students-data-check.component.scss
  src/app/components/diploma-supplement/students-data-check/students-data-check.component.ts
  src/app/models/CourseName.ts
Labels: refactoring

#199 use ag-grid column definition for column selection
  src/app/components/students/constants.ts
  src/app/components/students/students-columns/students-columns.component.html
  src/app/components/students/students-columns/students-columns.component.scss
  src/app/components/students/students-columns/students-columns.component.ts
  src/app/components/students/students-in-vacation/students-in-vacation.component.ts
  src/app/components/students/students.component.html
  src/app/components/students/students.component.ts
  src/app/components/students/students.module.ts
  src/app/components/students/translations.js
Labels: refactoring

#201 enhancement: exam-report: use select instead of radio
  src/app/components/additional-documents/additional-documents.component.html
  src/app/components/exam-report/exam-report.component.html
Labels: enhancement

#203 reusable students table
  src/app/components/students/expelled-students/expelled-students.component.html
  src/app/components/students/expelled-students/expelled-students.component.scss
  src/app/components/students/expelled-students/expelled-students.component.ts
  src/app/components/students/students-in-vacation/students-in-vacation.component.html
  src/app/components/students/students-in-vacation/students-in-vacation.component.scss
  src/app/components/students/students-in-vacation/students-in-vacation.component.ts
  src/app/components/students/students-table/students-table.component.html
  src/app/components/students/students-table/students-table.component.scss
  src/app/components/students/students-table/students-table.component.spec.ts
  src/app/components/students/students-table/students-table.component.ts
  src/app/components/students/students.component.ts
  src/app/components/students/students.module.ts
Labels: refactoring

#215 Feature view courses less name
  src/app/components/diploma-supplement/courses-translation-check/courses-translation-check.component.html
  src/app/components/diploma-supplement/courses-translation-check/courses-translation-check.component.scss
  src/app/components/diploma-supplement/courses-translation-check/courses-translation-check.component.spec.ts
  src/app/components/diploma-supplement/courses-translation-check/courses-translation-check.component.ts
  src/app/components/diploma-supplement/diploma-supplement.component.html
  src/app/components/diploma-supplement/diploma-supplement.component.ts
  src/app/components/diploma-supplement/diploma-supplement.module.ts
  src/app/models/custom/DataForSupplementCourseTranslationCheck.ts
  src/app/services/diploma-supplement.service.ts
Labels: new feature

#217 216 feat/hours per credits in courses for groups
  src/app/components/courses-for-groups/courses-for-groups.component.html
  src/app/components/courses-for-groups/courses-for-groups.component.scss
  src/app/components/courses-for-groups/courses-for-groups.component.ts
  src/app/services/course.service.ts
Labels: new feature
