Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2019-11, with the labels that each got.

#345 337 complement/add new course to drop down list
  src/app/components/courses-for-groups/course-creation/course-creation.component.ts
Labels: complement feature

#349 #331 thesis import save button: enhance: set button disabled when no …
  src/app/components/students/student-thesis-theme-input/student-thesis-theme-input.component.html
  src/app/components/students/student-thesis-theme-input/student-thesis-theme-input.component.ts
Labels: enhancement

#350 316 feat/show not relevant specializations
  src/app/components/specialization/recovery-specialization/recovery-specialization.component.html
  src/app/components/specialization/recovery-specialization/recovery-specialization.component.scss
  src/app/components/specialization/recovery-specialization/recovery-specialization.component.spec.ts
  src/app/components/specialization/recovery-specialization/recovery-specialization.component.ts
  src/app/components/specialization/specialization.component.html
  src/app/components/specialization/specialization.component.ts
  src/app/components/specialization/specialization.module.ts
  src/app/services/specialization.service.ts
Labels: new feature

#357 343 complement feature/enhance debtors report
  src/app/components/reports/debtors-statistics/debtor-statistics.component.html
  src/app/models/reports/debtors-statistics/SpecializationDebtorsYearStatistics.ts
Labels: Doc Team, complement feature

#354 #353 new-feature: set button for download rating was done
  src/app/components/students/student-stipend/student-stipend.component.html
  src/app/components/students/student-stipend/student-stipend.component.ts
  src/app/services/student-stipend.service.ts
Labels: Doc Team, new feature

#364 Rewrite notifications
  package-lock.json
  package.json
  src/app/components/app/app.module.ts
  src/app/components/courses-for-groups/course-creation/course-creation.component.ts
  src/app/components/courses-for-groups/courses-for-groups.component.html
  src/app/components/courses-for-groups/courses-for-groups.component.ts
  src/app/components/courses-for-groups/courses-for-groups.module.ts
  src/app/components/department/department.component.ts
  src/app/components/department/department.module.ts
  src/app/components/group/delete-group/delete-group.component.ts
  src/app/components/group/group.component.html
  src/app/components/group/group.component.ts
  src/app/components/group/group.module.ts
  src/app/components/group/recovery-group/recovery-group.component.ts
  src/app/components/shared/alerts/alerts-config.ts
  src/app/components/shared/alerts/alerts.module.ts
  src/app/components/shared/alerts/alerts.service.ts
  src/app/components/shared/alerts/models/alert-options.ts
  src/app/components/shared/alerts/models/toastr-adapter.ts
  src/app/components/teachers/teachers.component.html
  src/app/components/teachers/teachers.module.ts
  src/styles.scss
Labels: enhancement, refactoring
