Repository chdtu-fitis/deanoffice-frontend, pull requests merged in 2020-12, with the labels that each got.

#459 455 feat/selective courses statement
  src/app/components/exam-report/exam-report.component.html
  src/app/components/exam-report/exam-report.component.ts
  src/app/components/exam-report/exam-report.module.ts
  src/app/models/SelectiveCourse.ts
  src/app/services/exam-report.service.ts
  src/app/services/selective-course.service.ts
Labels: new feature

#463 #461 selective courses: sort assigned courses and make the left panel…
  src/app/components/selective-course/assigned-courses/assigned-courses.component.ts
  src/app/components/selective-course/selective-course.component.html
Labels: SelectiveCoursesTeam, enhancement

#462 #460 grades: add support for selective groups
  src/app/components/grade/grade.component.html
  src/app/components/grade/grade.component.ts
  src/app/components/grade/grades-panel/grades-panel.component.html
  src/app/components/grade/grades-panel/grades-panel.component.scss
  src/app/components/grade/grades-panel/grades-panel.component.ts
  src/app/components/selective-course/registered-students/registered-students.component.ts
  src/app/services/grade.service.ts
  src/app/services/selective-course.service.ts
Labels: SelectiveCoursesTeam
